### Hello
GET http://localhost:3005/hello

### Catalog
GET http://localhost:3005/catalog/books

### Buy
POST http://localhost:3005/commands/buy
content-type: application/json

{
    "price": 100,
    "id": "cane"
}